---

user_name: maykin
group_name: staff
project_name: vng
target: production
project_root: "/srv/sites/{{ project_name }}-{{ target }}"
project_src_dir: "vng"
celery_worker_path: "vng"
django_settings_module: "{{ project_src_dir }}.conf.{{ target }}"

pub_key_users:
  - alex
  - joeri
  - steven
  - jorik

project_repo: git@github.com:VNG-Realisatie/api-test-platform-code.git
branch: master

nginx_server_name: "api-test.nl"
nginx_access_log_file: "{{ project_root }}/log/nginx/access.log"
nginx_error_log_file: "{{ project_root }}/log/nginx/error.log"
nginx_static_dir: "{{ project_root }}/static/"
nginx_media_dir: "{{ project_root }}/media/"

dbname: vngatvprod
dbuser: vngatv
# dbpassword: (see vault)
dbport: 5432

uwsgi_port: 8084
shields_port: 9000

gcloud_project_id: vng-test-platform
gcloud_compute_zone: europe-west4-a
gcloud_cluster_name: test-sessions

node_version: 16
